version: '3'
services:
  web:
    build: .
    image: kaniabi/test-oauth2-server:dev
    ports:
      - "8880:80"
    environment:
      - DATABASE_URL=postgres://oauth2:oauth2@db:5432/oauth2
      - DJANGO_SECRET_KEY=secret123
      - PGUSER=oauth2
      - PGPASSWORD=oauth2
      - PGDATABASE=oauth2
      - PGHOST=db
  db:
    image: uhinfra/postgis:v3
    environment:
      - POSTGRES_USER=oauth2
      - POSTGRES_PASSWORD=oauth2
      - POSTGRES_DB=oauth2
    volumes:
      - test-oauth2-server-database:/var/lib/postgresql/data

volumes:
  test-oauth2-server-database:
