version: '3'
services:
  app:
    container_name: myauth-app
    build: .
    image: kaniabi/myauth:dev
    ports:
      - "8880:80"
    environment:
      - DATABASE_URL=postgres://myauth:myauth@db:5432/myauth
      - DJANGO_SECRET_KEY=secret123
      - DJANGO_DEBUG=True
  db:
    container_name: myauth-db
    image: uhinfra/postgis:v3
    environment:
      - POSTGRES_USER=myauth
      - POSTGRES_PASSWORD=myauth
      - POSTGRES_DB=myauth
    volumes:
      - myauth-db:/var/lib/postgresql/data

volumes:
  myauth-db:
